name: domain

dependencies:
- base >= 4.7 && < 5
- text == 1.2.3.1
- time == 1.8.0.2
library:
  source-dirs: src

tests:
  haskell-arch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - domain
