name: console-adapter

dependencies:
- base >= 4.7 && < 5
- usecase-defs
- text == 1.2.3.1

library:
  source-dirs: src

tests:
  haskell-arch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - usecase-defs
